# callpeak.sub 
# HTCondor submit file with for
# adding rg-ids and marking duplicates on bam files
# Run: condor_submit markduplicates_multi.sub

# Line added to ensure node has access to staging
Requirements = (Target.hasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://broadinstitute/gatk:4.6.1.0
universe = container

# Specify executable and arguments
# 
executable = markduplicates.sh
arguments = $(reads) $(rglb) $(rgpl) $(rgpu) $(rgsm)
   		
# specify name of the log, standard error, and standard output files 
# $(Cluster) represents queue number assigned to this set of jobs at the time of submission
# $(Process) is integer number for each job starting from "0"
log = $(reads)_$(Cluster)_$(Process).log
error = $(reads)_$(Cluster)_$(Process).err
output = $(reads)_$(Cluster)_$(Process).out
   
# transfer files in/out of /home/{net-id}/
# transfer output files on exit from compute node
should_transfer_files = YES
transfer_input_files = 
when_to_transfer_output = ON_EXIT
   
# memory, disk, and cpu requirements
request_cpus = 4
request_memory = 24GB
request_disk = 20GB
   
# Tell HTCondor to queue over a samplesheet.txt file
queue reads from samplesheet.txt

###END
